# Generated by Django 4.2 on 2026-01-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_fileupload_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='category',
            field=models.CharField(choices=[('notes', 'Notes'), ('past_papers', 'Past Papers'), ('assignments', 'Assignments')], default='notes', max_length=20),
        ),
    ]
