# Generated by Django 4.2 on 2026-01-04 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
