# Generated by Django 5.2.10 on 2026-01-07 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_fileupload_download_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='semester',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2')], default=1),
        ),
    ]
