# Generated by Django 5.2.10 on 2026-01-07 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_fileupload_archived_fileupload_uploaded_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('from_email', models.CharField(blank=True, max_length=255)),
                ('recipients', models.TextField(blank=True)),
                ('sent', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
